manifest_version = 1

[package]
name = "example-js-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example Javascript component for data collection"
documentation = "https://github.com/edgee-cloud/example-js-component"
repository = "https://github.com/edgee-cloud/example-js-component"
wit-world-version = "0.4.0"

[package.build]
command = "npm install && npx jco types wit/ -o types/ && npm run build && mv ./example-js-component.wasm ./dc-component.wasm"
output_path = "./example-js-component.wasm"
